Added ReaderServiceImplTest test.
djavorek/software-testing pull request #36
Opened 2018-12-01 19:49 UTC by sormanzje

2018-12-02 09:22 UTC, djavorek commented on bundle/service/src/test/java/hu/uni/miskolc/iit/swtest/team3/service/ReaderServiceImplTest.java
> +        when(testBookDao.read()).thenThrow((new UnsuccessfulOperationException("Could not get the list of books!")));
Dao needs to throw DataAccessException, that is catched by service and throws the Unsuccessful..Exception

2018-12-02 09:55 UTC, aronnagy commented on bundle/service/src/test/java/hu/uni/miskolc/iit/swtest/team3/service/ReaderServiceImplTest.java
> +        when(testBookDao.read()).thenThrow((new UnsuccessfulOperationException("Could not get the list of books!")));
Thanks for the advice! Now It is fixed and works well. (For more info check the next commit).

2018-12-02 13:23 UTC, djavorek commented
It still looks like there are uncovered lines :|

2018-12-02 18:40 UTC, djavorek requested changes

2018-12-02 18:40 UTC, djavorek commented on bundle/service/src/test/java/hu/uni/miskolc/iit/swtest/team3/service/ReaderServiceImplTest.java
> +        Mockito.when(testBookDao.read()).thenThrow(Mockito.mock(DataAccessException.class)).thenReturn(testBookList);
Is .thenReturn neccessary?

2018-12-02 18:40 UTC, djavorek commented on bundle/service/src/test/java/hu/uni/miskolc/iit/swtest/team3/service/ReaderServiceImplTest.java
> +        Mockito.when(testBorrowingDao.readByUser(testUser)).thenThrow(Mockito.mock(DataAccessException.class)).thenReturn(testBorrowingList);
Is .thenReturn neccessary?

2018-12-02 18:40 UTC, djavorek commented on bundle/service/src/test/java/hu/uni/miskolc/iit/swtest/team3/service/ReaderServiceImplTest.java
> +        Mockito.when(testBookDao.read(testBook.getIsbn())).thenThrow(Mockito.mock(DataAccessException.class)).thenReturn(testBook);
Is .thenReturn neccessary?

2018-12-02 18:40 UTC, djavorek commented on bundle/service/src/test/java/hu/uni/miskolc/iit/swtest/team3/service/ReaderServiceImplTest.java
> +        if(testBook.getAvailableCopies() > 0){
How does this work?
How many available copies the "testBook" has
If you want to check both if and else you should do it in separate test or something.
I dont think using if is a good idea here

2018-12-02 18:40 UTC, djavorek commented on bundle/service/src/test/java/hu/uni/miskolc/iit/swtest/team3/service/ReaderServiceImplTest.java
> +        if(testBook.getAvailableCopies() > 0){
Which one do you test?
If or else it wont check the two in the same time

2018-12-03 11:41 UTC, djavorek approved these changes

2018-12-03 11:42 UTC, merged